### ISSUE TITLE
タスクの進行状況確認用のInspectorツールの実装

### ISSUE THREAD

**Issue by naoyuki-sakai** [wbap/oculomotor#6]

**Comment by miyosuda** [comment]
<img width="920" alt="monitor_ui" src="https://user-images.githubusercontent.com/537493/45279597-9b079300-b50c-11e8-9920-51281b559f70.png">

@ktnyt 上記の画面の様な、Content-ID, 難易度の選択のUIを入れたいのですが、可能でしょうか？
(面倒であれば、プルダウンとかでもかまいません)

各タスクの難易度の種類は、以下のようになっていまして、

| Content| Difficulty | タスク名                          |
|:------:|:----------:|:--------------------------------:|
| 1      | None,0~2   | Point To Target                  |
| 2      | None,0~4   | Change Detection                 |
| 3      | None       | Odd One Out                      |
| 4      | None,0~5   | Visual Search                    |
| 5      | None,0~5   | Multiple Object Detection        |
| 6      | None,0~4   | Random Dot Motion Discrimination |

```
content = ChangeDetectionContent(difficulty=2)
```
とか、
```
content = ChangeDetectionContent(difficulty=None)
```
みたいな感じで、contentを作っていただければ。
(Odd One Ontだけ、難易度の指定がないので、
```
content = OddOneOutContent()
```
となります。

**Comment by miyosuda** [comment]
@ktnyt 
oculoenvに対して、
- Contentクラスのコンストラクタのdifficultyのデフォルト引数を`None`から`-1`に変更
-  OddOneOutContentのコンストラクタに`difficulty=-1`のデフォルト引数を追加
と変更したものを`feature/difficulty_arg` にpush しました。
https://github.com/wbap/oculoenv/tree/feature/difficulty_arg

masterへの反映と、pypiへの反映はまだです。
(pypiへは、version=0.1.1として反映する予定)

**Comment by miyosuda** [comment]
@ktnyt 
上記の修正を、oculoenv  pypi version=0.1.1として更新して反映しました。

**Comment by miyosuda** [comment]
こちら対応済みで、マージまで完了しています

**Comment by naoyuki-sakai** [comment]
ご対応いただき、ありがとうございます。
クローズします。
