### ISSUE TITLE
Retina と LIP のパラメータを修正する

### ISSUE THREAD

**Issue by naoyuki-sakai** [wbap/oculomotor#76]
インターンのフィードバックを受けて Retina と LIP のパラメータを修正してください。

**Comment by miyosuda** [comment]
LIPの方のSaliencyの方の調整していて、

https://github.com/wbap/oculomotor/blob/02b3a833278d69dc3a9238a5bb0b3ca0df45f7d3/application/functions/lip.py#L139-L143

こんな感じで、本田さん版のパラメータと、もともとのパラメータを切り替えられるようにして、確認してみました。
(また、RGBの各チャンネルでとったsaliencyを平均していたものを、maxを取るように変更しました)

## もともとの調整パラメータ (SALIENCY_ENHANCE_COEFF = 2.0)

![out_1_001](https://user-images.githubusercontent.com/537493/45536577-e687ad00-b83c-11e8-847a-a3af08c4777c.png)
![out_1_002](https://user-images.githubusercontent.com/537493/45536578-e7204380-b83c-11e8-84dc-163e375736a0.png)

![out_3_004](https://user-images.githubusercontent.com/537493/45536625-015a2180-b83d-11e8-9711-dfc5ffa60599.png)

![out_3_010](https://user-images.githubusercontent.com/537493/45536646-1040d400-b83d-11e8-82b9-e5d4cf657c04.png)

## 調整したもの (SALIENCY_ENHANCE_COEFF = 0.5)
![out_1_001](https://user-images.githubusercontent.com/537493/45536704-36667400-b83d-11e8-96a8-6088396d4dac.png)
![out_1_002](https://user-images.githubusercontent.com/537493/45536705-36ff0a80-b83d-11e8-9a66-3f53c8e2e83b.png)
![out_3_004](https://user-images.githubusercontent.com/537493/45536752-5ac25080-b83d-11e8-80a1-e9a0abf5c0fa.png)
![out_3_010](https://user-images.githubusercontent.com/537493/45536755-5dbd4100-b83d-11e8-8a8d-3b4ea90267c2.png)

上から二つ目の様な大きなEのサリエンシーがわかりにくくなる時は、`SALIENCY_ENHANCE_COEFF = 0.5`でも見えなくなっているので、ここの係数は元のままの方にして、Retinaのぼかし方の方の調整をした方がいいように思いました。

**Comment by miyosuda** [comment]
今のRetinaのぼかし方で、問題があるのは、
![out_3_003](https://user-images.githubusercontent.com/537493/45537014-1b483400-b83e-11e8-8fe0-1f192f7dd9e8.png)

![out_3_015](https://user-images.githubusercontent.com/537493/45536985-07043700-b83e-11e8-8d6d-2dd9c805f9fc.png)
![out_3_016](https://user-images.githubusercontent.com/537493/45536987-08cdfa80-b83e-11e8-93a5-92b2f27a2766.png)
一番下の段の様に、背景が黒の時に、赤い十時カーソルが完全に視覚的にも見えなくなってしまう様な周辺視処理になっているので、これは調整しないとダメそうです。

**Comment by miyosuda** [comment]
![out_3_003](https://user-images.githubusercontent.com/537493/45540656-f8bb1880-b847-11e8-8744-60282cd5ba7f.png)
![out_3_003](https://user-images.githubusercontent.com/537493/45540661-fbb60900-b847-11e8-914d-45c6ace9e92c.png)


![out_3_016](https://user-images.githubusercontent.com/537493/45540722-1be5c800-b848-11e8-88ae-9bfb59f0f981.png)
![out_3_016](https://user-images.githubusercontent.com/537493/45540742-2a33e400-b848-11e8-96a1-edc5ca192ca1.png)


![out_4_006](https://user-images.githubusercontent.com/537493/45540784-4899df80-b848-11e8-9ac0-d57215bdb529.png)
![out_4_006](https://user-images.githubusercontent.com/537493/45540793-4d5e9380-b848-11e8-9f4f-ed7eaf2a3d5d.png)

上段がオリジナル、下段が周辺視を調整したもの
赤いカーソルが微妙に見えているので、サリエンシーが出ているのと、周辺部分での色の判別が若干可能になっている。

**Comment by miyosuda** [comment]
Retiaのぼかし方を調整しました。
上段が元のもの、で下段が調整後のものです。
ひとまず、LIP, Retinaの調整は一旦こちらで終了いたします。

![out_3_010](https://user-images.githubusercontent.com/537493/45553198-35016f80-b86e-11e8-9e8c-f2f9b913801d.png)
![out_3_010](https://user-images.githubusercontent.com/537493/45553205-37fc6000-b86e-11e8-942c-ad8269c9618a.png)
![out_3_016](https://user-images.githubusercontent.com/537493/45553218-3df24100-b86e-11e8-83fe-8cc3f727c9af.png)
![out_3_016](https://user-images.githubusercontent.com/537493/45553223-40ed3180-b86e-11e8-881b-40ea8e614f24.png)
![out_3_018](https://user-images.githubusercontent.com/537493/45553240-4cd8f380-b86e-11e8-8fe0-7b879a1ba6b2.png)
![out_3_018](https://user-images.githubusercontent.com/537493/45553267-5febc380-b86e-11e8-9ee1-2080595c93ed.png)
![out_4_001](https://user-images.githubusercontent.com/537493/45553277-667a3b00-b86e-11e8-871c-192c4d3ace9f.png)
![out_4_001](https://user-images.githubusercontent.com/537493/45553281-69752b80-b86e-11e8-984c-4df698cb613a.png)
![out_4_006](https://user-images.githubusercontent.com/537493/45553305-7eea5580-b86e-11e8-9413-b53d56386f3f.png)
![out_4_006](https://user-images.githubusercontent.com/537493/45553310-814caf80-b86e-11e8-9d10-f8f448e52272.png)

**Comment by miyosuda** [comment]
こちら対応済みで、マージまで完了しています

**Comment by naoyuki-sakai** [comment]
ご対応いただき、ありがとうございます。
重要な仕事と思います。
クローズしますね。
