### ISSUE TITLE
Odd One Outタスクで、Trial開始直後に答えた状態になる場合があるバグ

### ISSUE THREAD

**Issue by miyosuda** [wbap/oculomotor#77]
Odd One Outで、仲間はずれのターゲットが、画面の中心にあった場合十時カーソル到達後に、Trialがはじまった時、その直後に正解状態となって、Trialが終わってしまう。

そのため、中心がターゲットとはならないように修正しなくてはいけない
<img width="100" alt="odd_one_out_task_bug" src="https://user-images.githubusercontent.com/537493/45404482-1d718d80-b69a-11e8-9def-488d69cd1c4f.png">

**Comment by miyosuda** [comment]
こちらoculoenvの方を修正して、pypiにも反映しました。(version=0.1.2)

**Comment by miyosuda** [comment]
こちら対応済みで、マージまで完了しています

**Comment by naoyuki-sakai** [comment]
ご対応いただき、ありがとうございます。
クローズします。
